executable = /afs/cern.ch/work/d/dneff/git/x17_trig/condor/reduce.sh
arguments = $(inp) $(outp)
output = /afs/cern.ch/work/d/dneff/git/x17_trig/condor/logs/$(tag).out
error = /afs/cern.ch/work/d/dneff/git/x17_trig/condor/logs/$(tag).err
log = /afs/cern.ch/work/d/dneff/git/x17_trig/condor/logs/condor.log
+JobFlavour = "microcentury"
request_memory = 6000
requirements = (OpSysAndVer =?= "AlmaLinux9")
should_transfer_files = NO
queue inp,outp,tag from /afs/cern.ch/work/d/dneff/git/x17_trig/condor/list.txt
